name = "universal-cf-gateway-mvp-alpha"
main = "src/index.ts"
compatibility_date = "2026-03-10"
workers_dev = true

[[queues.producers]]
binding = "HTTP_WEBHOOK_QUEUE"
queue = "universal-cf-gateway-alpha-http-webhook"

[[queues.consumers]]
queue = "universal-cf-gateway-alpha-http-webhook"
max_batch_size = 5
max_batch_timeout = 60
max_retries = 3

[[queues.producers]]
binding = "ALPHA_BATCH_WEBHOOK_QUEUE"
queue = "universal-cf-gateway-alpha-batch-webhook"

[[queues.consumers]]
queue = "universal-cf-gateway-alpha-batch-webhook"
max_batch_size = 5
max_batch_timeout = 60
max_retries = 3

[[kv_namespaces]]
binding = "COLD_PATH_KV"
id = "f1cf05245a584c309d0fca2719027854"

[[durable_objects.bindings]]
name = "COORDINATOR"
class_name = "CoordinatorDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CoordinatorDO"]

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true
